all:
	gcc -O0 -std=c99 -o rand_read rand_read.c 
	gcc -O0 -std=c99 -o rand_write rand_write.c 
	gcc -O0 -std=c99 -o rand_test rand_test.c 
	gcc -O0 -std=c99 -o seq seq.c
	gcc -O0 -std=c99 -o seq_read seq_read.c
	gcc -O0 -std=c99 -o zero zero.c
	gcc -O0 -std=c99 -o zero_read zero_read.c
